#
# ESP-IDF Build Pipeline
#
name: idf_build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: install esp-idf
        run: |
          git clone --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh
      - name: build design
        run: |
          source ./esp-idf/export.sh
          ls
          idf.py build
